AWPO_WebMobile/Controllers/T_OfficersVacanciesMasterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AWPO_WebMobile.DbModel;
using AWPO_WebMobile.App_Code;

namespace AWPO_WebMobile.Controllers
{
    public class T_OfficersVacanciesMasterController : Controller
    {
        private AWPODBEntities db = new AWPODBEntities();
        CommonFunctions ObjCommonFunctions = new CommonFunctions();

        // GET: T_OfficersVacanciesMaster
        public ActionResult Index_officers_Vacancies()
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            var VacancyList = from s in db.T_OfficersVacanciesMaster.Where(s=>s.TypOfVacancy=="1").OrderByDescending(s=>s.OfficersVacancyID) select s;
            IList<T_OfficersVacanciesMaster> ObjList = new List<T_OfficersVacanciesMaster>();
            foreach (var vacanciesMaster in VacancyList)
            {
                T_OfficersVacanciesMaster Obj = new T_OfficersVacanciesMaster();
                //string vac= CommonFunctions.getVacancyTypeById(Convert.ToInt32(vacanciesMaster.TypOfVacancy)); ;
                //Obj.TypOfVacancy = vac;
                Obj.OfficersVacancyID = vacanciesMaster.OfficersVacancyID;
                Obj.CompanyName = vacanciesMaster.CompanyName;
                Obj.NoOfPost = vacanciesMaster.NoOfPost;
                Obj.Post = vacanciesMaster.Post;
                Obj.Salary = vacanciesMaster.Salary;
                Obj.Location = vacanciesMaster.Location;
                Obj.QR = vacanciesMaster.QR;
                Obj.PostedDate = vacanciesMaster.PostedDate;
                Obj.LastDate = vacanciesMaster.LastDate;
                Obj.Exam_InterviewDate = vacanciesMaster.Exam_InterviewDate;
                Obj.Remarks = vacanciesMaster.Remarks;
                ObjList.Add(Obj);
            };
            return View(ObjList);
            //return View(await db.T_OfficersVacanciesMaster.ToListAsync());
        }

        public ActionResult Index_JCO_OCR()
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            var VacancyList = from s in db.T_OfficersVacanciesMaster.Where(s => s.TypOfVacancy == "2").OrderByDescending(s => s.OfficersVacancyID) select s;
            IList<T_OfficersVacanciesMaster> ObjList = new List<T_OfficersVacanciesMaster>();
            foreach (var vacanciesMaster in VacancyList)
            {
                T_OfficersVacanciesMaster Obj = new T_OfficersVacanciesMaster();
                Obj.OfficersVacancyID = vacanciesMaster.OfficersVacancyID;
                Obj.CompanyName = vacanciesMaster.CompanyName;
                Obj.NoOfPost = vacanciesMaster.NoOfPost;
                Obj.Post = vacanciesMaster.Post;
                Obj.Salary = vacanciesMaster.Salary;
                Obj.Location = vacanciesMaster.Location;
                Obj.QR = vacanciesMaster.QR;
                Obj.PostedDate = vacanciesMaster.PostedDate;
                Obj.LastDate = vacanciesMaster.LastDate;
                Obj.Exam_InterviewDate = vacanciesMaster.Exam_InterviewDate;
                Obj.Remarks = vacanciesMaster.Remarks;
                ObjList.Add(Obj);
            };
            return View(ObjList);
            //return View(await db.T_OfficersVacanciesMaster.ToListAsync());
        }

        public ActionResult Index_Govt_Comp()
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            var VacancyList = from s in db.T_OfficersVacanciesMaster.Where(s => s.TypOfVacancy == "3").OrderByDescending(s => s.OfficersVacancyID) select s;
            IList<T_OfficersVacanciesMaster> ObjList = new List<T_OfficersVacanciesMaster>();
            foreach (var vacanciesMaster in VacancyList)
            {
                T_OfficersVacanciesMaster Obj = new T_OfficersVacanciesMaster();
                Obj.OfficersVacancyID = vacanciesMaster.OfficersVacancyID;
                Obj.CompanyName = vacanciesMaster.CompanyName;
                Obj.NoOfPost = vacanciesMaster.NoOfPost;
                Obj.Post = vacanciesMaster.Post;
                Obj.Salary = vacanciesMaster.Salary;
                Obj.Location = vacanciesMaster.Location;
                Obj.QR = vacanciesMaster.QR;
                Obj.PostedDate = vacanciesMaster.PostedDate;
                Obj.LastDate = vacanciesMaster.LastDate;
                Obj.Exam_InterviewDate = vacanciesMaster.Exam_InterviewDate;
                Obj.Remarks = vacanciesMaster.Remarks;
                ObjList.Add(Obj);
            };
            return View(ObjList);
            //return View(await db.T_OfficersVacanciesMaster.ToListAsync());
        }

        // GET: T_OfficersVacanciesMaster/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            T_OfficersVacanciesMaster t_OfficersVacanciesMaster = await db.T_OfficersVacanciesMaster.FindAsync(id);
            if (t_OfficersVacanciesMaster == null)
            {
                return HttpNotFound();
            }
            return View(t_OfficersVacanciesMaster);
        }

        // GET: T_OfficersVacanciesMaster/Create
        public ActionResult Create_officers_Vacancies()
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }

            return View();
        }

        // POST: T_OfficersVacanciesMaster/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create_officers_Vacancies([Bind(Include = "CompanyName,NoOfPost,Post,Salary,Location,QR,PostedDate,LastDate,Exam_InterviewDate,Remarks")] T_OfficersVacanciesMaster t_OfficersVacanciesMaster)
        {
            if (ModelState.IsValid)
            {
                t_OfficersVacanciesMaster.TypOfVacancy = "1";
                t_OfficersVacanciesMaster.CreatedBy = "Admin";
                t_OfficersVacanciesMaster.CreatedDate = DateTime.Now;
                t_OfficersVacanciesMaster.ModifiedBy = "Admin";
                t_OfficersVacanciesMaster.ModifiedDate = DateTime.Now;
                t_OfficersVacanciesMaster.Active = true;
                db.T_OfficersVacanciesMaster.Add(t_OfficersVacanciesMaster);
                await db.SaveChangesAsync();
                return RedirectToAction("Index_officers_Vacancies");
            }
            return View(t_OfficersVacanciesMaster);
        }

        // GET: T_OfficersVacanciesMaster/Create
        public ActionResult Create_JCO_OCR()
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }

            return View();
        }

        // POST: T_OfficersVacanciesMaster/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create_JCO_OCR([Bind(Include = "CompanyName,NoOfPost,Post,Salary,Location,QR,PostedDate,LastDate,Exam_InterviewDate,Remarks")] T_OfficersVacanciesMaster t_OfficersVacanciesMaster)
        {
            if (ModelState.IsValid)
            {
                t_OfficersVacanciesMaster.TypOfVacancy = "2";
                t_OfficersVacanciesMaster.CreatedBy = "Admin";
                t_OfficersVacanciesMaster.CreatedDate = DateTime.Now;
                t_OfficersVacanciesMaster.ModifiedBy = "Admin";
                t_OfficersVacanciesMaster.ModifiedDate = DateTime.Now;
                t_OfficersVacanciesMaster.Active = true;
                db.T_OfficersVacanciesMaster.Add(t_OfficersVacanciesMaster);
                await db.SaveChangesAsync();
                return RedirectToAction("Index_JCO_OCR");
            }
            return View(t_OfficersVacanciesMaster);
        }


        // GET: T_OfficersVacanciesMaster/Create
        public ActionResult Create_Govt_Comp()
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            return View();
        }

        // POST: T_OfficersVacanciesMaster/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create_Govt_Comp([Bind(Include = "CompanyName,NoOfPost,Post,Salary,Location,QR,PostedDate,LastDate,Exam_InterviewDate,Remarks")] T_OfficersVacanciesMaster t_OfficersVacanciesMaster)
        {
            if (ModelState.IsValid)
            {
                t_OfficersVacanciesMaster.TypOfVacancy = "3";
                t_OfficersVacanciesMaster.CreatedBy = "Admin";
                t_OfficersVacanciesMaster.CreatedDate = DateTime.Now;
                t_OfficersVacanciesMaster.ModifiedBy = "Admin";
                t_OfficersVacanciesMaster.ModifiedDate = DateTime.Now;
                t_OfficersVacanciesMaster.Active = true;

AWPO_WebMobile/Views/T_OfficersVacanciesMaster/Create_Govt_Comp.cshtml
@model AWPO_WebMobile.DbModel.T_OfficersVacanciesMaster

@{
    ViewBag.Title = "Create_Govt_Comp";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Create Govt & Comp</h2>


    @using (Html.BeginForm("Create_Govt_Comp", "T_OfficersVacanciesMaster", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
                    @Html.LabelFor(model => model.TypOfVacancy, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TypOfVacancy", ViewBag.EnumList as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TypOfVacancy, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NoOfPost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoOfPost, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoOfPost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Post, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Post, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Post, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QR, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.QR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QR, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PostedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostedDate, new { htmlAttributes = new { @class = "form-control CalanderUI" } })
                    @Html.ValidationMessageFor(model => model.PostedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastDate, new { htmlAttributes = new { @class = "form-control CalanderUI" } })
                    @Html.ValidationMessageFor(model => model.LastDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Exam_InterviewDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Exam_InterviewDate, new { htmlAttributes = new { @class = "form-control CalanderUI" } })
                    @Html.ValidationMessageFor(model => model.Exam_InterviewDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index_Govt_Comp")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

AWPO_WebMobile/Views/T_OfficersVacanciesMaster/Create_JCO_OCR.cshtml
@model AWPO_WebMobile.DbModel.T_OfficersVacanciesMaster

@{
    ViewBag.Title = "Create_JCO_OCR";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Create JCO & OCR</h2>


    @using (Html.BeginForm("Create_JCO_OCR", "T_OfficersVacanciesMaster", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
                    @Html.LabelFor(model => model.TypOfVacancy, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TypOfVacancy", ViewBag.EnumList as SelectList, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TypOfVacancy, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NoOfPost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoOfPost, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoOfPost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Post, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Post, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Post, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QR, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.QR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QR, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PostedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostedDate, new { htmlAttributes = new { @class = "form-control CalanderUI" } })
                    @Html.ValidationMessageFor(model => model.PostedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastDate, new { htmlAttributes = new { @class = "form-control CalanderUI" } })
                    @Html.ValidationMessageFor(model => model.LastDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Exam_InterviewDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Exam_InterviewDate, new { htmlAttributes = new { @class = "form-control CalanderUI" } })
                    @Html.ValidationMessageFor(model => model.Exam_InterviewDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("Back to List", "Index_JCO_OCR")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AWPO_WebMobile/Views/T_OfficersVacanciesMaster/Create_officers_Vacancies.cshtml
@model AWPO_WebMobile.DbModel.T_OfficersVacanciesMaster

@{
    ViewBag.Title = "Create Officers Vacancies";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <h2>Create Officers Vacancies</h2>
    @using (Html.BeginForm("Create_officers_Vacancies", "T_OfficersVacanciesMaster", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NoOfPost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoOfPost, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoOfPost, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Post, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Post, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Post, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.QR, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.QR, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QR, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PostedDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostedDate, new { htmlAttributes = new { @class = "form-control CalanderUI" } })
                    @Html.ValidationMessageFor(model => model.PostedDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastDate, new { htmlAttributes = new { @class = "form-control CalanderUI" } })
                    @Html.ValidationMessageFor(model => model.LastDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Exam_InterviewDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Exam_InterviewDate, new { htmlAttributes = new { @class = "form-control CalanderUI" } })
                    @Html.ValidationMessageFor(model => model.Exam_InterviewDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

</div>

<div>
    @Html.ActionLink("Back to List", "Index_officers_Vacancies")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AWPO_WebMobile/Views/T_OfficersVacanciesMaster/Delete_Govt_Comp.cshtml
@model AWPO_WebMobile.DbModel.T_OfficersVacanciesMaster

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container shadow p-2"></div>
<h2>Delete Govt Comp : <small>Are you sure you want to delete this?</small></h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoOfPost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoOfPost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Post)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Exam_InterviewDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Exam_InterviewDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Remarks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>        
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index_Govt_Comp")
        </div>
    }
</div>