AWPO_WebMobile/Controllers/M_ExamMaterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AWPO_WebMobile.DbModel;
using AWPO_WebMobile.App_Code;

namespace AWPO_WebMobile.Controllers
{
    public class M_ExamMaterController : Controller
    {
        private AWPODBEntities db = new AWPODBEntities();

        // GET: M_ExamMater
        public async Task<ActionResult> Index()
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            return View(await db.M_ExamMater.ToListAsync());
        }

        // GET: M_ExamMater/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            M_ExamMater m_ExamMater = await db.M_ExamMater.FindAsync(id);
            if (m_ExamMater == null)
            {
                return HttpNotFound();
            }
            return View(m_ExamMater);
        }

        // GET: M_ExamMater/Create
        public ActionResult Create()
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            return View();
        }

        // POST: M_ExamMater/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                M_ExamMater m_ExamMater = new M_ExamMater();
                string StudentImagePath = null;
                if (!string.IsNullOrEmpty(Request.Files["PdfPath"].FileName))
                {
                    string FolderPath = Server.MapPath(Resources.AWPOResources.TextNewImagesPath);// + "\\" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_" + DateTime.Now.Day + "_" + DateTime.Now.DayOfWeek;
                    string FullPathWithFileName = FolderPath + "\\" + Request.Files["PdfPath"].FileName;
                    string FolderPathForImage = Request.Files["PdfPath"].FileName;  //"\\" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_" + DateTime.Now.Day + "_" + DateTime.Now.DayOfWeek + "\\" + Request.Files["StdProfilePicPath"].FileName;
                    if (CommonFunctions.IsFolderExist(FolderPath))
                    {
                        Request.Files["PdfPath"].SaveAs(FullPathWithFileName);
                        StudentImagePath = FolderPathForImage;
                    }
                }
                m_ExamMater.PdfPath = StudentImagePath;
                m_ExamMater.ExamName = collection["ExamName"].ToString();
                m_ExamMater.Location = "NA";
                m_ExamMater.Description = "NA";
                m_ExamMater.CreatedBy = "Admin";
                m_ExamMater.CreatedDate = DateTime.Now;
                m_ExamMater.ModifiedBy = "Admin";
                m_ExamMater.ModifiedDate = DateTime.Now;
                m_ExamMater.Active = true;
                db.M_ExamMater.Add(m_ExamMater);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Message = "Error Due To : "+ ex.ToString();
            }
            return View();
        }

        // GET: M_ExamMater/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            M_ExamMater m_ExamMater = await db.M_ExamMater.FindAsync(id);
            if (m_ExamMater == null)
            {
                return HttpNotFound();
            }
            return View(m_ExamMater);
        }

        // POST: M_ExamMater/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit_Post(FormCollection collection)
        {
            try
            {
                M_ExamMater m_ExamMater = new M_ExamMater();
                string StudentImagePath = null;
                if (!string.IsNullOrEmpty(Request.Files["PdfPath"].FileName))
                {
                    string FolderPath = Server.MapPath(Resources.AWPOResources.TextNewImagesPath);// + "\\" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_" + DateTime.Now.Day + "_" + DateTime.Now.DayOfWeek;
                    string FullPathWithFileName = FolderPath + "\\" + Request.Files["PdfPath"].FileName;
                    string FolderPathForImage = Request.Files["PdfPath"].FileName;  //"\\" + DateTime.Now.Year + "_" + DateTime.Now.Month + "_" + DateTime.Now.Day + "_" + DateTime.Now.DayOfWeek + "\\" + Request.Files["StdProfilePicPath"].FileName;
                    if (CommonFunctions.IsFolderExist(FolderPath))
                    {
                        Request.Files["PdfPath"].SaveAs(FullPathWithFileName);
                        StudentImagePath = FolderPathForImage;
                    }
                }
                m_ExamMater.ExamID= Convert.ToInt32(collection["ExamID"]);
                m_ExamMater.PdfPath = StudentImagePath;
                m_ExamMater.ExamName = collection["ExamName"].ToString();
                m_ExamMater.Location = "NA";
                m_ExamMater.Description = "NA";
                m_ExamMater.CreatedBy = "Admin";
                m_ExamMater.CreatedDate = DateTime.Now;
                m_ExamMater.ModifiedBy = "Admin";
                m_ExamMater.ModifiedDate = DateTime.Now;
                m_ExamMater.Active = true;
                db.Entry(m_ExamMater).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Error Due To : " + ex.ToString();
            }
            return View();
        }

        // GET: M_ExamMater/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (!CommonFunctions.CheckUserAuthentication())
            {
                return RedirectToAction("Login", "Admin");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            M_ExamMater m_ExamMater = await db.M_ExamMater.FindAsync(id);
            if (m_ExamMater == null)
            {
                return HttpNotFound();
            }
            return View(m_ExamMater);
        }

        // POST: M_ExamMater/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            M_ExamMater m_ExamMater = await db.M_ExamMater.FindAsync(id);
            db.M_ExamMater.Remove(m_ExamMater);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AWPO_WebMobile/Views/M_ExamMater/Create.cshtml
@model AWPO_WebMobile.DbModel.M_ExamMater

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Create : <small>Exam Pattern</small></h2>

    @using (Html.BeginForm("Create", "M_ExamMater", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ExamName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ExamName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExamName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PdfPath, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" id="PdfPath" name="PdfPath" class="form-control" style="display:block" multiple="multiple" />
                    @*@Html.EditorFor(model => model.PdfPath, new { htmlAttributes = new { @class = "form-control" } })*@
                    @Html.ValidationMessageFor(model => model.PdfPath, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AWPO_WebMobile/Views/M_ExamMater/Delete.cshtml
@model AWPO_WebMobile.DbModel.M_ExamMater

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Delete : <small>Are you sure you want to delete this?</small></h2>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ExamName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ExamName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PdfPath)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PdfPath)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-warning" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

AWPO_WebMobile/Views/M_ExamMater/Details.cshtml
@model AWPO_WebMobile.DbModel.M_ExamMater

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Details : <small>Exam Pattern</small></h2>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ExamName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ExamName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PdfPath)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PdfPath)
            </dd>

           
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ExamID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

AWPO_WebMobile/Views/M_ExamMater/Edit.cshtml
@model AWPO_WebMobile.DbModel.M_ExamMater

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    @using (Html.BeginForm("Edit", "M_ExamMater", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h4>Edit : Exam Pattern</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ExamID)

            <div class="form-group">
                @Html.LabelFor(model => model.ExamName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ExamName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExamName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PdfPath, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" id="PdfPath" name="PdfPath" class="form-control" style="display:block" multiple="multiple" />
                    @Html.ValidationMessageFor(model => model.PdfPath, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-warning" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

AWPO_WebMobile/Views/M_ExamMater/Index.cshtml
@model IEnumerable<AWPO_WebMobile.DbModel.M_ExamMater>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <h2>Index : <small>Exam Pattern</small></h2>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table table-striped table-hover table-bordered">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ExamName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PdfPath)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ExamName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PdfPath)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.ExamID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.ExamID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.ExamID })
                </td>
            </tr>
        }

    </table>
</div>